version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: |
    git submodule init
    git submodule update
    create-project.bat %PLATFORM% %CONFIGURATION%
    build-project.bat  %PLATFORM% %CONFIGURATION%
